FROM node:18

WORKDIR /app

COPY ./index.js ./index.js
COPY ./models ./models
COPY ./middleware ./middleware
COPY ./routes ./routes
COPY ./utils ./utils
COPY ./package.json ./package.json
# COPY ./env ./env

RUN npm install

EXPOSE 8000

CMD ["node", "index.js"]